FROM ubuntu:latest

# Set the default environment variables
ENV LOCATION=docker-mobile
ENV DEBIAN_FRONTEND=noninteractive
ENV HOME=/mobile
# ENV LAUNCH_COMMAND="serve -s build"

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    curl \
    wget \
    git \
    nano \
    unzip \
    software-properties-common \
    sudo

# Update the system and install required packages
RUN apt update && apt upgrade -y && \
    apt install -y npm xsel wget unzip zip && \
    npm cache clean --force && \
    apt clean

# Install Amazon Corretto (OpenJDK 11)
RUN file_name=amazon-corretto-21-x64-linux-jdk.deb && \
    wget https://corretto.aws/downloads/latest/$file_name && \
    apt install -y ./$file_name && \
    rm $file_name

# Updating environement paths
ENV ANDROID_HOME /usr/local/android-sdk-linux
ENV PATH "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"

# Install Android SDK Command-Line Tools
RUN mkdir -p ${ANDROID_HOME} && \
    cd ${ANDROID_HOME} && \
    wget -q https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip && \
    unzip commandlinetools-linux-7302050_latest.zip && \
    rm commandlinetools-linux-7302050_latest.zip && \
    mv cmdline-tools tools && \
    mkdir cmdline-tools && \
    mv tools cmdline-tools/latest

# Accept licenses and install platform tools and the SDK
RUN yes | sdkmanager --sdk_root=${ANDROID_HOME} --licenses && \
    sdkmanager --sdk_root=${ANDROID_HOME} "platform-tools" "platforms;android-30"

# Set the working directory in the Docker container
WORKDIR ${HOME}

# Copy your project files to the container
COPY . ${HOME}

# Source SDKMAN, ensure gradlew has execute permissions and use gradlew to build the project
RUN if [ -f "./gradlew" ]; then chmod +x ./gradlew \
    && ./gradlew assembleRelease; \
    else echo "gradlew not found"; fi

# Copy APK from the build stage to the final image
# COPY --from=build /mobile/app/build/outputs/apk/release/app-release.apk /output/app-release.apk

# Install npm dependencies
RUN timeout 60s npm install && npm cache clean --force || timeout 60s npm install && npm cache clean --force

# Build the project (optional, uncomment if you want to build here)
# RUN npm run build

# Expose the ports that need to be used
EXPOSE 1024-9000

# Entry point
# CMD ["/bin/bash","-c", "${LAUNCH_COMMAND}" ]
CMD ["/bin/bash"]
